format_version: 3
pipelines:
  public-blog:
    group: blog-public
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - test:
          clean_workspace: true
          environment_variables:
            KUDU_ENVIRONMENT: testing
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks generate
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks demo_host
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test
                - exec:
                    run_if: any
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks cleanup
      - release:
          clean_workspace: true
          jobs:
            code:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
      - publish:
          clean_workspace: true
          environment_variables:
            KUDU_ENVIRONMENT: production
          jobs:
            publish:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks generate
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish
