version: 2.1

workflows:
  # Environment variables required in CircleCI environment:
  #  - GITHUB_CREDENTIALS
  public-blog:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
      - publish:
          requires:
            - release
          filters:
            branches:
              only: master

jobs:
  test:
    environment:
      KUDU_ENVIRONMENT: testing
    executor: platform
    steps:
      - setup
      - run:
          command: ./tasks generate
      - run:
          command: ./tasks demo_host
      - run:
          command: ./tasks test
      - run:
          command: ./tasks cleanup

  release:
    executor: platform
    steps:
      - setup
      - run:
          command: ./tasks release

  publish:
    environment:
      KUDU_ENVIRONMENT: production
    executor: platform
    steps:
      - setup
      - run:
          command: /bin/bash -c "git config --global user.email \"ewa@kudulab.io\""
      - run:
          command: /bin/bash -c "git config --global user.name \"xmik\""
      - run:
          command: ./tasks generate
      - run:
          command: ./tasks publish

commands:
  setup:
    steps:
      - checkout

executors:
  platform:
    machine:
      image: ubuntu-2004:202101-01
    working_directory: ~/repo
