baseurl = "https://kudulab.io"
title = "KuduLab"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "ait-lab"
googleAnalytics = "UA-138356014-1"

[params]
    #author = " Doe"
    description = "John Doe's personal website"

    keywords = "blog,developer,personal"
    # footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    author_tom = "Tomasz Sętkowski"
    tom_info = "DevOps | Software Developer"
    tom_avatarurl = "/images/tom_avatar.png"

    author_ewa = "Ewa Chechowska"
    ewa_info = "DevOps Engineer"
    ewa_avatarurl = "/images/ewa_avatar.png"

[taxonomies]
  series = "series"

[[params.tom_social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/tomzo/"
[[params.tom_social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/tomaszsetkowski/"
[[params.tom_social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/tomzo/"

[[params.ewa_social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/xmik/"
[[params.ewa_social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/czechowska/"


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "Home"
        weight = 1
        url = "/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"

        [[languages.en.menu.main]]
        name = "About"
        weight = 5
        url = "/contact/"
